name: Sodium Dev CI

on:
  push:
    branches: [ dev, 'renovate/*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle
          
      - name: Build
        run: gradle build
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle
          
      - name: Test
        run: gradle check
        
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-artifacts
          path: lib/build/reports/jacoco/test/jacocoTestReport.xml
          
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle

      - name: Package
        run: gradle assemble

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-artifacts
          path: lib/build/libs/*.jar