name: Sodium Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle
          
      - name: Build
        run: gradle build
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle
          
      - name: Test
        run: gradle check
        
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-artifacts
          path: lib/build/reports/jacoco/test/jacocoTestReport.xml
