name: Sodium Main CI

on:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          #cache: gradle
          
      - name: Package
        run: gradle assemble
        
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package-artifacts
          path: lib/build/libs/*.jar
